name: CreativePlugin
main: fr.tenkei.creaplugin.MyPlugin
author: Thenkei
version: 1.2.0
commands:
  build:
    aliases: [bp, tpbuild]
  rejoindre:
    aliases: [join]
  accepter:
    aliases: [yes]
  spawn:
  buyhome:
  home:
    aliases: [h, maison]
  sethome:
  hps:
    aliases: [argent]
  jetons:
    aliases: [jeton]
  head:
    aliases: [tete]
  tppos:
  tp:
  tphere:
    aliases: [s]
  tpbiome:
  tphome:
  tpold:
  tuto:
  protection:
  setspawn: