name: HeavenFun
main: fr.heavencraft.heavenfun.HeavenFun
version: 1.0
commands:
#
# HeavenCore
#
  creacheat:
  endercheat:
  inventory:
  tp:
  tphere:
    aliases: s
  tppos:
  tpworld:
#
# HeavenFun
#
  spawn: