main: fr.lorgan17.lorganserver.LorganServer
name: LorganServer
version: 0.1
commands:

  endercheat:
  gc:
  inventory:
  roucoups:
  tp:
  tphere:
  tppos:

  setspawn:

  lit:
  protection:
  spawn: